{{- range $name, $secret := .Values.secrets }}
{{- if $secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xatu-kafka.fullname" $ }}-{{ $name }}
  labels:
    strimzi.io/cluster: {{ include "xatu-kafka.fullname" $ }}
    {{- include "xatu-kafka.labels" $ | nindent 4 }}
stringData:
 {{- tpl (toString ($secret.stringData | toYaml)) $ | nindent 2 }}
{{- end }}
---
{{- end }}