{{- range $name, $topic := .Values.topics }}
{{- if $topic.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $name }}
  labels:
    strimzi.io/cluster: {{ include "xatu-kafka.fullname" $ }}
    {{- include "xatu-kafka.labels" $ | nindent 4 }}
spec:
 {{- tpl (toString ($topic.spec | toYaml)) $ | nindent 2 }}
{{- end }}
---
{{- end }}