xatu-cannon:
  fullnameOverride: xatu-cannon

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 512Mi

  config:
    logging: "info"
    metricsAddr: ":9090"
    pprofAddr: ":6060"
    name: "xatu-eth-cannon-dsrv"
    ethereum:
      beaconNodeAddress: https://cl.eth.rootwarp.dev
      beaconNodeHeaders: {} #FILL_ME
      blockCacheSize: 3000
      blockCacheTtl: 3h
      blockPreloadWorkers: 15
    coordinator:
      address: xatu-server.xatu-eth.svc.cluster.local:8080
      # tls: true
      # headers:
      #   authorization: FILL_ME
    outputs:
    - name: grpc
      type: xatu
      config:
        address: xatu-server.xatu-eth.svc.cluster.local:8080
        maxQueueSize: 1000000
        # tls: true
        # headers:
        #   authorization: FILL_ME
        maxExportBatchSize: 64
    - name: stdout
      type: stdout
