xatu-mimicry:
  fullnameOverride: xatu-mimicry

  resources:
    limits:
      cpu: 1024m
      memory: 1536Mi
    requests:
      cpu: 512m
      memory: 512Mi

  terminationGracePeriodSeconds: 300

  config:
    logging: "info"
    metricsAddr: ":9090"
    pprofAddr: ":6060"
    probeAddr: ":8080"
    captureDelay: 3m
    name:  "xatu-eth-mimicry-dsrv"
    coordinator:
      type: xatu
      config:
        address: xatu-server.xatu-eth.svc.cluster.local:8080
        maxPeers: 100
        networkIds:
        - 1
        forkIdHashes:
        - "0xdce96c2d"
    outputs:
    - name: grpc
      type: xatu
      config:
        address: xatu-server.xatu-eth.svc.cluster.local:8080
        maxExportBatchSize: 32
    - name: stdout
      type: stdout
