xatu-discovery:
  fullnameOverride: xatu-discovery

  resources: 
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi

  config:
    logging: "info"
    metricsAddr: ":9090"
    pprofAddr: ":6060"
    coordinator:
      address: xatu-server.xatu-over.svc.cluster.local:8080
      maxQueueSize: 51200
      batchTimeout: 5s
      exportTimeout: 30s
      maxExportBatchSize: 512
      concurrentExecutionPeers: 100
    p2p:
      # type: xatu
      # config:
      #   bootNodes: []
      #   discV4: true
      #   discV5: true
      #   restart: 2m
      #   networkIds:
      #   - 1
      #   forkIdHashes:
      #   - "0xdce96c2d"
      type: static
      config:
        discV4: true
        discV5: true
        restart: 2m
        bootNodes:
        - enr:-LG4QIehoH_dl7wlQmMx8-OEfIW-0yeI-rGRYSUAfn4drBkWFKD6_E1eYI_eCKhnBFkAKGWCqSJQofwao5tcC0fA-UeGAYxCc5YJh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIhZOX4RvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQJPVa6SZdUgrpt-7dvqzWGl1sHgt67F7A12lj4TGTjUPIN1ZHCCyyA
        - enr:-LG4QPEbXzBmfJw6aoZNwmAcmPpnqc9aNWyi7GaxQiXWmACPEL7xzDFet2_zfv6vHGXLFsody_0evlmhUJGSxCN5hfuGAYxCc5hch2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIiAbRYRvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQLk1EnqQhIUBEDlhEc6LFLDo2s85Obh-VH01LgcF8ErtYN1ZHCCyyA
        - enr:-LG4QLIBhccIkeJfY-on14-iRUTCfhZYCaOeLuFP5uqogBBiDOndaX1we4N6nilzIOGn45HLDwncj-FmAETzK9bGZXSGAYxCc5dmh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEI-xrLoRvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQKFg1P2iLJD-3h9yd6S4YpUDjElrY6To4x8Em8E2DRU6oN1ZHCCyyA
        - enr:-MK4QOk-eEpO_WTLBjms0wwvYY2uXAONUSjcsWfTA_AqimYvTJ_w3MSJQytn67P0foI7RshZ6NMYwqCrvbXtLxYoO46GAYxiETvoh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIlFsboRvdmVykMNUqrYgAACS_v________-Jc2VjcDI1NmsxoQO-I2FrA9lvQ2nzh9zkDx0YU13Pvb1gXEIasRyAaXSmR4hzeW5jbmV0cwCDdGNwgs8Ig3VkcILLIA
        - enr:-MK4QMLchE3W_rEkk0uCsF4tvdwb71lIrLu0xCo4QgQ4OLstHvmPmAZfZleppraxmnD4Htx33CWBF8PRl1lZQZIsxcKGAYxiJ5IDh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIlC5pIRvdmVykMNUqrYgAACS_v________-Jc2VjcDI1NmsxoQJ_M4wFuL659vDhvNs41rIhZiWPTG4GuPUl5z-u2_duIIhzeW5jbmV0cwCDdGNwgs8Ig3VkcILLIA
        - enr:-MK4QPZ1RsVfAWplK4M6hCDvJ2bvUDxp6sgV_n6zGVUQCywFIa-Tzyr-nq9XY2D7gxjjYp9TNlVVvloZ9bdhdGORmNmGAYxiKH4eh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIlEgg4RvdmVykMNUqrYgAACS_v________-Jc2VjcDI1NmsxoQK8QBQHtv2Zwx2JQCfuXWFO_tHvmwsR4oi8h-N7iQgGwIhzeW5jbmV0cwCDdGNwgs8Ig3VkcILLIA
        - enr:-MK4QHgSgJk7GoU9chphPiOHZNCQshuAELlxgYj5GoIJTQYBGHme-qnL5uaNHiunN1OBnlJsKjWAMKeFcTBZL1ZGg86GAYxhQU-_h2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIkCvx4RvdmVykMNUqrYgAACS_v________-Jc2VjcDI1NmsxoQJpCr4M5ksdwOXj-_nmJ2LfWowuO-0ApPjNb2urrK6zu4hzeW5jbmV0cwCDdGNwgs8Ig3VkcILLIA
        - enr:-MK4QPGcsBNG2A61EH5sqTgi2AmayKKlJIT0efhDX_G2hYVBVZF4Z-ot2kukuUOtuyeew0R6a3rf1RhzajPJaClYMsqGAYxiJDZLh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIkBpk4RvdmVykMNUqrYgAACS_v________-Jc2VjcDI1NmsxoQL0slNJJjVikDboXwU_qmEYZWmZu3wTah5-o4dWKK5EHohzeW5jbmV0cwCDdGNwgs8Ig3VkcILLIA
