xatu-discovery:
  fullnameOverride: xatu-discovery

  resources: 
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi

  config:
    logging: "info"
    metricsAddr: ":9090"
    pprofAddr: ":6060"
    coordinator:
      address: xatu-server.xatu-over.svc.cluster.local:8080
      maxQueueSize: 51200
      batchTimeout: 5s
      exportTimeout: 30s
      maxExportBatchSize: 512
      concurrentExecutionPeers: 100
    p2p:
      # type: xatu
      # config:
      #   bootNodes: []
      #   discV4: true
      #   discV5: true
      #   restart: 2m
      #   networkIds:
      #   - 1
      #   forkIdHashes:
      #   - "0xdce96c2d"
      type: static
      config:
        discV4: true
        discV5: true
        restart: 2m
        bootNodes:
          #################################
          # Over - Allay
          #################################
          - enr:-LG4QHXnaI_vnTR-0O0vCaL5wENl-wsi6LY00Q7gX3MVs3UXNBO0DR_7VI27PX9anqx87Eet20_H9PN4BLseARfWS5GGAYs5FUKOh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEI-oVPoRvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQKnsJbfnrMNU0d2bgAz9egXpXkkXq0ncPITqZxu4FaLQYN1ZHCCLuA
          - enr:-LG4QNTkZVe77ruEzRq_D1msu6orDXs5BYcxIggWTWbWjaAWK6m5rxH5XScldrsi2p39FU8GuLr-4N0UZTzURkJyk2mGAYs5FUOmh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIhIZioRvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQP5FqjFsDxTCkLvt78vf693EtoT1Q_zrbsxqejveKiDxoN1ZHCCLuA
          - enr:-LG4QGh-2ZeknOGVVlK2uBeOmkOddp2JP3tvmNNswDTy3CQuW3kd9KS3Ery-c10aRPzBZxPVs6n6LOhNaEzWleoBI5mGAYs5FUVLh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIqXW2oRvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQKisejSerU7owKPh8hitntn5rSgvpGZTj-aMicxTZ2saYN1ZHCCLuA
          - enr:-LG4QGlLjtMBNO9PCJ_aUmmplEkq4FhPg8KOQ8ZOqelFdLQNJSgvdVLkB79glxYfXTGk9A8t1pnFaInaXMwTo1s6r9aGAYs5FUQ2h2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIl8YxYRvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQKs9_qbDUmz1t8EqE50NUCGXBVf-_UAL1ZAHgb1ME_Es4N1ZHCCLuA
          - enr:-LG4QFzBYbVnV55I1O5NEpT19GSvWo1IqVzcXXvhBqFQTqOmMPYp98DGJKdxxOQYsS9w4dzDZLv6SPzUHkpF-G9oqJ2GAYs5FUUyh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEI8dKH4RvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQPAoJUz7CgSxHsDlK070QONYAUyXH6Ds1iTAHwx7ktGTIN1ZHCCLuA
          - enr:-LG4QFfV21S9L_JIwVRM5_D7n0QCjN0fLASBiMq-m-24I1HoICkHNy9Q7sZIqS9qTt9wfnC0jAVwmHiMlbVbfJW8zk-GAYs5FUT2h2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIrCSNIRvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQJ8ftm-y1SrBis3PV3754bBFmDP0TXfaKwa5Y64iDb0BIN1ZHCCLuA
          - enr:-LG4QJVO6b4cNeAKVE4hbWIhfFBHdDKD5zPxoO7T05G2dZz0P6oLZo7Dw6d6xT2djNqFIUoU-SCdJT8TMdPJWhWn-DyGAYs5FURoh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIil99YRvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQOA2431YVQWfXubSyao6d7jsWCYGYMrPoBJVdpvpDDamoN1ZHCCLuA
          - enr:-LG4QHF6Zx6Brw8fmjWqCz14DSuoJrb_ksU8rwfnpZYC9VMEHFkcSKzUwsO2FHMGIBunnfZ-oqrvQUbYOmK5qJWdASyGAYs5FUTzh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIopEFYRvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQJy1KTNVUUpgkS7Uaqmkx_d9LpmLjokXpJl5TO-YVYJjYN1ZHCCLuA
          - enr:-LG4QD_5yVFKDwSHSvYUYiIJMywy5l0_DBqXNxXy6izzMmGmdKJ1iYCRrclOEmNjXb_AngDjcT_D5swUM_wFZxQDQI6GAYs5FURXh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIq4eaYRvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQOTS6ZhSUTjpsKNBvmcriugGAf-Nvlm_dryC_wEU6IPCoN1ZHCCLuA
          - enr:-LG4QGfxdhbQdnDSTfFhVo5rzPbFduSTL7tzlTBzBf7DNWGoUnSukD58xDaLA12Ty_wBhbLqIkpih88liuOmRnxZWlqGAYs5FUQih2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIl73e4RvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQPSC2ariwinqWcyr7e5Fd3PO5H8HfxZHlmOioxgyGvtPYN1ZHCCLuA
          - enr:-LG4QE0x3ydPiLkWmBM4GQ1Ju7tJWaKGjLjgxU9yfrQd4XQPFwLDecl2W8hbaXsLNIH1wi-v7iQRw3sWwOoZajZZMEmGAYs5FUHch2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIkAvvoRvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQOHsgESVTsZfPrJVK3MH5MHNzt5M6Tc6LwX3b1acNivIYN1ZHCCLuA
          - enr:-LG4QD-AqbyMX8Ob44ORYmkGa3ru2kYtbnDic_TBQ8SHqQ2nY7HDT9b9ST3cLleN7J3StBW7xlSSeMbvOYc1V19mkT2GAYs5FUNch2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIl1xmoRvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQPkM7tiQqMA2HFoTFussOSJSVjriR5aKXNze3_jzAQoj4N1ZHCCLuA
          - enr:-LG4QDcvo3VXKQpGQ2CBy4j109aH1i7EFabWyrgL2VwpSHYkDhAsLJmHM9DX8B121TuiZ-GZJMFA45xbkzDO_mcaVLaGAYs5FUKvh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEInyxh4RvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQJhQOxLa6gfqVLlDhomFMSZ-fQFyi9CVoqx5ldC7c2Z1YN1ZHCCLuA
          - enr:-LG4QIf5uMTJSSuR-TerEPthZqp53AGjMglHYtTBxydxBJcVU9aIgSH92Okw_pPksAcVUTKGDcQt_T4km7qtSiMta4aGAYs5FUN5h2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEI_Rjt4RvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQKyVxmHSUxYgxK0VZDmq5tKzLUWWD6lqhiTPcI4zj6bboN1ZHCCLuA
          - enr:-LG4QEDvX51awHprTmVP7wqovAzI_fzpDJreOZzj2dPiDegWWy0zQrhA2fhtIJBc2o09NA5B9vcm3FfE26kiF1b11sSGAYs5FUVPh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEInYI4YRvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQLLpoUWWjvfvCqNQkwszDfdr7fdwZ5wbhL6ouGK-7IbnYN1ZHCCLuA
          - enr:-LG4QOSxDBhKZcSCLmOobzWolK4lFLKs5TP4wtlV3IHASicNca2hcibMhFUBpgvYJvVoQxhFe-W3Voqf2YAxK1rBM42GAYs5FUSih2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIljtfoRvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQO8v5kowO0yjUMXxCc4zEfw6zdsAV61QdYgfzbpfEh364N1ZHCCLuA
          - enr:-LG4QD_Jo60TJnTOaGqI81E9562KoFqgPCO5NFmAZJVrOKcgBSBkWWtnjBVuS8HF1O4fHB4-sM8aSx69k8ytPb3Xe5uGAYs5FUVBh2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIq9VNIRvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQJnJqfcs27FkGZcyHYAoaSvaqCXqKZqiaE15VUlw7bnFIN1ZHCCLuA
          - enr:-LG4QIYxSb_8MOq1COI9Piu6j3G54NYuI6z_LOlzPzt65o5LSNa0XZ2GzShzZupQJil-o0aTPzFjaXuKYo6W9HhdVxaGAYs5FURch2F0dG5ldHOIAAAAAAAAAACCaWSCdjSCaXCEIkwSG4RvdmVykPWl_UIAAAAA__________-Jc2VjcDI1NmsxoQKjkOIJtGd-k7DjuwPM5_BL3Bg28IoxJO4jCci_qJfPmYN1ZHCCLuA
