fullnameOverride: xatu-kafka

labels:
  protocol: over

cluster:
  kafka:
    version: 3.5.0
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
    - name: external
      port: 9094
      tls: true
      type: loadbalancer
      authentication:
        type: scram-sha-512
    replicas: 2
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 300m
        memory: 4Gi
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        class: standard-gp3
        deleteClaim: false
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: eks.amazonaws.com/nodegroup
                  operator: In
                  values:
                  - ng-heavyload-blue
                  - ng-heavyload-green
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    config:
      message.max.bytes: 10485760 # 10MB
      replica.fetch.max.bytes: 10485760 # 10MB
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
      default.replication.factor: 2
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.4"
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: "{{ include \"xatu-kafka.fullname\" $ }}-config"
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: false
      class: standard-gp3
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: "{{ include \"xatu-kafka.fullname\" $ }}-config"
          key: zookeeper-metrics-config.yml
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: eks.amazonaws.com/nodegroup
                  operator: In
                  values:
                  - ng-heavyload-blue
                  - ng-heavyload-green
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"

users:
  xatu-kafka-external-vector:
    enabled: true
    spec: 
      authentication:
        type: scram-sha-512
        password:
          valueFrom:
            secretKeyRef:
              name: xatu-kafka-xatu
              key: password

secrets:
  xatu:
    enabled: true
    stringData:
      password: validators2023

topics:
  beacon-api-eth-v1-events-head:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v1-events-head-v2:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v1-events-block:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v1-events-block-v2:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v1-events-attestation:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 3600000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v1-events-attestation-v2:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 3600000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v1-events-voluntary-exit:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v1-events-voluntary-exit-v2:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v1-events-finalized-checkpoint:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v1-events-finalized-checkpoint-v2:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v1-events-chain-reorg:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v1-events-chain-reorg-v2:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v1-events-contribution-and-proof:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v1-events-contribution-and-proof-v2:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  mempool-transaction:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 3600000
        segment.bytes: 1073741824
        compression.type: snappy
  mempool-transaction-v2:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 3600000
        segment.bytes: 1073741824
        compression.type: snappy
        max.message.bytes: 10485760 # 10MB
  beacon-api-eth-v2-beacon-block:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 3600000
        segment.bytes: 1073741824
        compression.type: snappy
        max.message.bytes: 10485760 # 10MB
  beacon-api-eth-v2-beacon-block-v2:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 3600000
        segment.bytes: 1073741824
        compression.type: snappy
        max.message.bytes: 10485760 # 10MB
  beacon-api-eth-v1-debug-fork-choice:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 3600000
        segment.bytes: 1073741824
        compression.type: snappy
        max.message.bytes: 10485760 # 10MB
  beacon-api-eth-v1-debug-fork-choice-v2:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 3600000
        segment.bytes: 1073741824
        compression.type: snappy
        max.message.bytes: 10485760 # 10MB
  beacon-api-eth-v1-debug-fork-choice-reorg:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
        max.message.bytes: 10485760 # 10MB
  beacon-api-eth-v1-debug-fork-choice-reorg-v2:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
        max.message.bytes: 10485760 # 10MB
  beacon-api-eth-v1-beacon-committee:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 3600000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v1-validator-attestation-data:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 3600000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v2-beacon-block-proposer-slashing:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v2-beacon-block-attester-slashing:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v2-beacon-block-bls-to-execution-change:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v2-beacon-block-execution-transaction:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 3600000
        segment.bytes: 1073741824
        compression.type: snappy
        max.message.bytes: 10485760 # 10MB
  beacon-api-eth-v2-beacon-block-voluntary-exit:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v2-beacon-block-deposit:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
  beacon-api-eth-v2-beacon-block-withdrawal:
    enabled: true
    spec:
      partitions: 12
      replicas: 2
      config:
        retention.ms: 259200000
        segment.bytes: 1073741824
        compression.type: snappy
